plugins {
    id 'net.neoforged.gradleutils' version '3.0.0'
    id 'dev.lukebemish.immaculate' version '0.1.6' apply false
}

project.version = project.neoforge_version

// Print version, generally useful to know - also appears on CI
System.out.println("NeoForge version ${project.version}")

allprojects {
    version rootProject.version
    group 'net.neoforged'
    repositories {
        maven { url = 'https://hub.spigotmc.org/nexus/content/groups/public/' }
        maven { url = 'https://maven.mohistmc.com/' }
        maven { url = 'https://maven.izzel.io/releases' }
        mavenLocal()
    }

    tasks.withType(JavaCompile).configureEach {
        options.encoding = 'UTF-8'
        options.compilerArgs << '-Xlint:-dep-ann' << '-Xlint:-removal' << '-Xdiags:verbose'
    }
}

subprojects {
    apply plugin: 'java'

    java.toolchain.languageVersion.set(JavaLanguageVersion.of(project.java_version))
}

repositories {
    mavenCentral()
}