pluginManagement {
    repositories {
        gradlePluginPortal()
        mavenLocal()
        maven { url = 'https://hub.spigotmc.org/nexus/content/groups/public/' }
        maven { url = 'https://maven.mohistmc.com/' }
        /*Only Dev*/maven { url = 'https://maven.neoforged.net/releases' }
    }
}

plugins {
    id 'net.neoforged.moddev.repositories' version "${moddevgradle_plugin_version}"
    id 'org.gradle.toolchains.foojay-resolver-convention' version '0.8.0'
}

// This makes the version available to buildSrc
gradle.ext.moddevgradle_plugin_version = moddevgradle_plugin_version
gradle.ext.minecraft_version = minecraft_version
gradle.ext.diffpatch_version = diffpatch_version
gradle.ext.asm_version = asm_version

dependencyResolutionManagement {
    repositoriesMode = RepositoriesMode.FAIL_ON_PROJECT_REPOS
    rulesMode = RulesMode.FAIL_ON_PROJECT_RULES
    repositories {
        mavenCentral()
        mavenLocal()
        maven { url = 'https://hub.spigotmc.org/nexus/content/groups/public/' }
        maven { url = 'https://maven.mohistmc.com/' }
        maven { url = 'https://maven.mohistmc.cn/releases'}
    }
    versionCatalogs {
        libs {
            // Terminal Console Appender.. essentually make pretty colors in the console, but it's been a PITA
            library('terminalconsoleappender', 'net.minecrell:terminalconsoleappender:1.4.0')
            version('jline', '3.25.1')
            library('jline-reader',       'org.jline', 'jline-reader'      ).versionRef('jline')
            library('jline-terminal',     'org.jline', 'jline-terminal'    ).versionRef('jline')
            library('jline-terminal-jna', 'org.jline', 'jline-terminal-jna').versionRef('jline') // Colors and tab completeion
            bundle('terminalconsoleappender', ['terminalconsoleappender', 'jline-reader', 'jline-terminal', 'jline-terminal-jna'])

            // These are libraries shipped by the MC launcher, try and keep them in sync with the manifest
            // but honestly if we don't it just means we ship them as normal libraries by adding them to the installer config in the forge project
            library('gson', 'com.google.code.gson:gson:2.10.1')
            library('guava', 'com.google.guava:guava:32.1.2-jre')
            library('failureaccess', 'com.google.guava:failureaccess:1.0.1')
            version('log4j', '2.22.1')
            library('log4j-api',  'org.apache.logging.log4j', 'log4j-api' ).versionRef('log4j')
            library('log4j-core', 'org.apache.logging.log4j', 'log4j-core').versionRef('log4j')
            library('log4j-iostreams', 'org.apache.logging.log4j', 'log4j-iostreams').versionRef('log4j')
            library('log4j-slf4j2-impl', 'org.apache.logging.log4j', 'log4j-slf4j2-impl').versionRef('log4j')
            bundle('log4j', ['log4j-api', 'log4j-core', 'log4j-iostreams', 'log4j-slf4j2-impl'])

            library('apache-commons', 'org.apache.commons:commons-lang3:3.14.0')
            library('mojang-logging', 'com.mojang:logging:1.2.7')
            library('jopt-simple', 'net.sf.jopt-simple:jopt-simple:5.0.4')
            library('commons-io', 'commons-io:commons-io:2.15.1')

            version('adventure', '4.14.0')
            library('adventure-api', 'net.kyori', 'adventure-api').versionRef('adventure')
            library('adventure-key', 'net.kyori', 'adventure-key').versionRef('adventure')
            library('minimessage', 'net.kyori', 'adventure-text-minimessage').versionRef('adventure')
            library('serializer-gson', 'net.kyori', 'adventure-text-serializer-gson').versionRef('adventure')
            library('serializer-json', 'net.kyori', 'adventure-text-serializer-json').versionRef('adventure')
            library('serializer-legacy', 'net.kyori', 'adventure-text-serializer-legacy').versionRef('adventure')
            library('serializer-plain', 'net.kyori', 'adventure-text-serializer-plain').versionRef('adventure')
            library('serializer-ansi', 'net.kyori', 'adventure-text-serializer-ansi').versionRef('adventure')
            library('text-logger-slf4j', 'net.kyori', 'adventure-text-logger-slf4j').versionRef('adventure')
            library('ansi', 'net.kyori:ansi:1.0.3')
            library('examination-api', 'net.kyori:examination-api:1.3.0')
            library('examination-string', 'net.kyori:examination-string:1.3.0')
            bundle('adventure', ['adventure-api', 'adventure-key', 'minimessage', 'serializer-gson', 'serializer-json', 'serializer-legacy', 'serializer-plain', 'serializer-ansi', 'text-logger-slf4j', 'ansi', 'examination-api', 'examination-string'])

            library('i18n', 'com.mohistmc:i18n:0.6')
            library('json', 'com.mohistmc:json:0.5')
            library('tools', 'com.mohistmc:tools:0.6')
            library('snakeyaml', 'org.yaml:snakeyaml:2.2')
            library('yaml', 'com.mohistmc:yaml:0.8')
            library('dynamicenum', 'com.mohistmc:dynamicenum:0.3.1')
            library('libraries', 'com.mohistmc:libraries:0.5')
            library('progressbar', 'me.tongfei:progressbar:0.10.0')
            library('orgjline', 'org.jline:jline:3.25.1')
        }
    }
}

if (rootProject.name.toLowerCase() == "youer") {
    // Solve name clashes between projects/neoforge and the rootProject for Eclipse.
    rootProject.name = "Youer-Root"
}

include ':base'
project(':base').projectDir = file('projects/base')
include ':youer'
project(':youer').projectDir = file('projects/youer')

include 'youerlauncher'

include ':coremods'
// Ensure a unique artifact id within JIJ that does not conflict with net.neoforged:coremods, which is
// another external dependency.
project(":coremods").name = "neoforge-coremods"

// Expose the repository base URLs to projects to be able to access them
// See this Gradle issue for tracking a more permanent solution:
// https://github.com/gradle/gradle/issues/27260
gradle.settingsEvaluated {
    gradle.extensions.add("repositoryBaseUrls", dependencyResolutionManagement.repositories.findAll { it instanceof MavenArtifactRepository }.collect { it.url }.toArray(URI[]::new))
}
