modLoader="minecraft"
license="Minecraft EULA"
licenseURL="https://aka.ms/MinecraftEULA"
[[mods]]
modId="minecraft"
version="${minecraft_version}"
displayName="Minecraft"
authors="Mojang Studios"
description=""
